[package]
name = "math_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
math_core = { path = "../math_core"}
wasm-bindgen-test = "0.3.50"

